#========================================================
# Practica 1: Hormiga de Langton
# Asignatura: Algoritmo y Estructura de Datos Avanzados (AEDA)
# Autor: Joel Francisco Escobar Socas
# Contacto: alu0101130408@ull.edu.es
# Grado: Ingeniería Informática (ETSII)
#========================================================

make: mundo.h mundo.cpp hormiga.h hormiga.cpp main.cpp
	g++ -g mundo.cpp hormiga.cpp main.cpp -o p1
clean: 
	echo "Eliminando el ejecutable..."
	rm -f p1